library(sqldf)
library(lubridate)

mydata <- read.csv.sql("household_power_consumption.txt", sql="select * from file where Date = '1/2/2007' or Date = '2/2/2007'",header=TRUE, sep=";")
mydata$Date<-strptime(paste(mydata$Date, mydata$Time, sep=" "),format = "%d/%m/%Y %H:%M:%S")

png(file="plot4.png",width=480, height=480, unit="px")
par(mfrow=c(2,2))
par(mar=c(4,4,1,1))
plot(mydata$Date, mydata$Global_active_power, type="l", xlab="",ylab="Global Active Power (kilowatts)")
plot(mydata$Date, mydata$Voltage, type="l" ,xlab="datetime",ylab="Voltage")
plot(mydata$Date, mydata$Sub_metering_1, type="l",xlab="",ylab="Energy sub metering")
lines(mydata$Date, mydata$Sub_metering_2, col="red")
lines(mydata$Date, mydata$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),border = NULL, pch="___",col=c("black","red","blue"))
plot(mydata$Date, mydata$Global_reactive_power, type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()