library(sqldf)
mydata <- read.csv.sql("household_power_consumption.txt", sql="select * from file where Date = '1/2/2007' or Date = '2/2/2007'",header=TRUE, sep=";")
hist(mydata$Global_active_power, xlab="Global Active Power (kilowatts)", main="Global Active Power", col = "RED")
dev.copy(png,file="plot1.png")
dev.off()